<script setup lang="ts">
const asset = useAsset()
</script>
<!-- Figma 727:2775: native, section-flow markup; interior coordinates retain the approved artwork crops. -->
<template>
  <StreetEditorialMobile />
  <section class="detail-editorial-section" style="position:relative;background:#0e0f0f;height:calc(875 * var(--u));left:auto;overflow:clip;top:auto;width:calc(1920 * var(--u));translate:none" data-design-node="727:2856">    <div style="position:absolute;left:calc(736 * var(--u));width:calc(785 * var(--u));height:calc(785 * var(--u));top:calc(45 * var(--u))" data-design-node="727:2857">      <div style="position:absolute;inset:-13.03%">        <img :src="asset('product-details/25521.svg')" alt="" loading="lazy" style="display:block;max-width:none;width:100%;height:100%" />
</div>
</div>
    <MotionTitle text="VI-1" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;line-height:calc(58 * var(--u));left:calc(80 * var(--u));font-style:normal;font-size:calc(48 * var(--u));color:#fff;top:calc(100 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:2858" />
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;line-height:calc(24 * var(--u));left:calc(80 * var(--u));font-style:normal;font-size:calc(20 * var(--u));color:rgba(255,255,255,0.8);top:calc(206 * var(--u));letter-spacing:calc(0.8 * var(--u));width:calc(554 * var(--u))" data-design-node="727:2859"> A forged wheel designed around the demands of everyday performance — balancing lightweight construction, structural strength and refined proportions for the modern performance vehicle. </p>
    <div style="position:absolute;height:0;left:calc(80 * var(--u));top:calc(182 * var(--u));width:calc(164 * var(--u))" data-design-node="727:2860">      <div style="position:absolute;inset:calc(-0.5 * var(--u)) 0">        <img :src="asset('product-details/98724.svg')" alt="" loading="lazy" style="display:block;max-width:none;width:100%;height:100%" />
</div>
</div>
    <a href="#engineering" class="editorial-link wipe-control" style="position:absolute;border-width:calc(1 * var(--u));border-style:solid;border-color:#fff;align-content:stretch;display:flex;align-items:flex-start;left:calc(80 * var(--u));padding-left:calc(24 * var(--u));padding-right:calc(24 * var(--u));padding-top:calc(10 * var(--u));padding-bottom:calc(10 * var(--u));top:calc(350 * var(--u))" data-design-node="727:2861">      <div style="align-content:stretch;display:flex;gap:calc(8 * var(--u));align-items:center;position:relative;flex-shrink:0" data-design-node="727:2862">        <p style="overflow-wrap:break-word;font-family:'Space Mono',monospace;line-height:calc(20 * var(--u));font-style:normal;position:relative;flex-shrink:0;font-size:calc(16 * var(--u));color:#fff;text-transform:uppercase;white-space:nowrap" data-design-node="727:2863"> learn more </p>
        <div style="position:relative;flex-shrink:0;width:calc(16 * var(--u));height:calc(16 * var(--u))" data-design-node="727:2864">          <ArrowIcon />
</div>
</div>
</a>
    <div style="position:absolute;display:contents;left:calc(776 * var(--u));top:calc(129 * var(--u))" data-design-node="727:2866">      <div style="position:absolute;left:calc(776 * var(--u));width:calc(709 * var(--u));height:calc(709 * var(--u));top:calc(129 * var(--u))" data-design-node="727:2867">        <img :src="asset('product-details/ddca6.webp')" alt="" loading="lazy" style="position:absolute;inset:0;max-width:none;object-fit:cover;pointer-events:none;width:100%;height:100%" />
</div>
</div>
</section>
  <section class="detail-editorial-section" id="engineering" style="position:relative;background:#0e0f0f;height:calc(862 * var(--u));left:auto;overflow:clip;top:auto;width:calc(1920 * var(--u));translate:none" data-design-node="727:3066">    <div style="overflow-wrap:break-word;position:absolute;display:contents;font-family:'Space Mono',monospace;left:calc(80 * var(--u));font-style:normal;top:calc(100 * var(--u))" data-design-node="727:3067">      <MotionTitle text="Engineered Beyond Design." style="position:absolute;line-height:calc(58 * var(--u));left:calc(80 * var(--u));font-size:calc(48 * var(--u));color:#fff;top:calc(100 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3068" />
      <p data-reveal="fade" style="position:absolute;line-height:calc(24 * var(--u));left:calc(80 * var(--u));font-size:calc(20 * var(--u));color:rgba(255,255,255,0.8);top:calc(182 * var(--u));letter-spacing:calc(0.8 * var(--u));width:calc(763 * var(--u))" data-design-node="727:3069"> Behind every VI-1 is a development process that connects digital engineering, material selection, manufacturing and validation. </p>
</div>
    <div style="position:absolute;display:contents;left:calc(80 * var(--u));top:calc(334 * var(--u))" data-design-node="727:3070">      <div style="position:absolute;height:calc(428 * var(--u));left:calc(80 * var(--u));top:calc(334 * var(--u));width:calc(422 * var(--u))" data-design-node="727:3071">        <img :src="asset('product-details/30fba.svg')" alt="" loading="lazy" style="position:absolute;display:block;inset:0;max-width:none;width:100%;height:100%" />
</div>
      <div style="position:absolute;height:calc(428 * var(--u));left:calc(526 * var(--u));top:calc(334 * var(--u));width:calc(422 * var(--u))" data-design-node="727:3073">        <img :src="asset('product-details/30fba.svg')" alt="" loading="lazy" style="position:absolute;display:block;inset:0;max-width:none;width:100%;height:100%" />
</div>
      <div style="position:absolute;height:calc(428 * var(--u));left:calc(972 * var(--u));top:calc(334 * var(--u));width:calc(422 * var(--u))" data-design-node="727:3075">        <img :src="asset('product-details/30fba.svg')" alt="" loading="lazy" style="position:absolute;display:block;inset:0;max-width:none;width:100%;height:100%" />
</div>
      <div style="position:absolute;height:calc(428 * var(--u));left:calc(1418 * var(--u));top:calc(334 * var(--u));width:calc(422 * var(--u))" data-design-node="727:3077">        <img :src="asset('product-details/30fba.svg')" alt="" loading="lazy" style="position:absolute;display:block;inset:0;max-width:none;width:100%;height:100%" />
</div>
      <div style="position:absolute;height:calc(320 * var(--u));left:calc(100 * var(--u));top:calc(358 * var(--u));width:calc(382 * var(--u))" data-design-node="727:3079">        <div style="position:absolute;inset:0;overflow:hidden;pointer-events:none">          <img :src="asset('product-details/ec3f8.webp')" alt="" loading="lazy" style="position:absolute;height:203.48%;left:0;max-width:none;top:0;width:306.19%" />
</div>
</div>
      <div style="position:absolute;height:calc(320 * var(--u));left:calc(546 * var(--u));top:calc(358 * var(--u));width:calc(382 * var(--u))" data-design-node="727:3080">        <div style="position:absolute;inset:0;overflow:hidden;pointer-events:none">          <img :src="asset('product-details/ec3f8.webp')" alt="" loading="lazy" style="position:absolute;height:203.48%;left:-102.91%;max-width:none;top:0;width:306.19%" />
</div>
</div>
      <div style="position:absolute;height:calc(320 * var(--u));left:calc(992 * var(--u));top:calc(358 * var(--u));width:calc(382 * var(--u))" data-design-node="727:3081">        <div style="position:absolute;inset:0;overflow:hidden;pointer-events:none">          <img :src="asset('product-details/ec3f8.webp')" alt="" loading="lazy" style="position:absolute;height:203.48%;left:-206.19%;max-width:none;top:0;width:306.19%" />
</div>
</div>
      <div style="position:absolute;height:calc(320 * var(--u));left:calc(1438 * var(--u));top:calc(358 * var(--u));width:calc(382 * var(--u))" data-design-node="727:3082">        <div style="position:absolute;inset:0;overflow:hidden;pointer-events:none">          <img :src="asset('product-details/ec3f8.webp')" alt="" loading="lazy" style="position:absolute;height:203.48%;left:0;max-width:none;top:-103.48%;width:306.19%" />
</div>
</div>
      <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;line-height:calc(28 * var(--u));left:calc(50% + calc(-860 * var(--u)));font-style:normal;font-size:calc(24 * var(--u));color:#fff;top:calc(698 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3083"> R-01 </p>
      <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;line-height:calc(28 * var(--u));left:calc(50% + calc(-414 * var(--u)));font-style:normal;font-size:calc(24 * var(--u));color:#fff;top:calc(698 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3084"> R-01 </p>
      <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;line-height:calc(28 * var(--u));left:calc(50% + calc(32 * var(--u)));font-style:normal;font-size:calc(24 * var(--u));color:#fff;top:calc(698 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3085"> R-01 </p>
      <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;line-height:calc(28 * var(--u));left:calc(50% + calc(478 * var(--u)));font-style:normal;font-size:calc(24 * var(--u));color:#fff;top:calc(698 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3086"> R-01 </p>
</div>
</section>
  <section class="detail-editorial-section" id="specifications" style="position:relative;background:#0e0f0f;height:calc(2298 * var(--u));left:auto;overflow:clip;top:auto;width:calc(1920 * var(--u));translate:none" data-design-node="727:3087">    <div style="position:absolute;height:calc(2880 * var(--u));left:50%;top:0;width:calc(1920 * var(--u));translate:-50% 0" data-design-node="727:3088">      <div style="position:absolute;inset:0;pointer-events:none">        <img :src="asset('product-details/2f6c8.webp')" alt="" loading="lazy" style="position:absolute;max-width:none;object-fit:cover;width:100%;height:100%" />
        <div style="position:absolute;background:rgba(0,0,0,0.6);inset:0"></div>
</div>
</div>
    <div style="position:absolute;display:flex;height:calc(3361 * var(--u));align-items:center;justify-content:center;left:50%;top:0;width:calc(1920 * var(--u));translate:-50% 0" data-design-node="727:3089">      <div style="flex:none;rotate:180deg">        <div style="background:linear-gradient(to top,var(--gradient-from),var(--gradient-to) var(--gradient-stop,100%));--gradient-from:#0e0f0f;height:calc(3361 * var(--u));position:relative;--gradient-to:rgba(14,15,15,0.07);width:calc(1920 * var(--u))"></div>
</div>
</div>
    <div style="position:absolute;display:contents;left:calc(80 * var(--u));top:calc(100 * var(--u))" data-design-node="727:3090">      <MotionTitle text="VI-1 Specifications" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;line-height:calc(58 * var(--u));left:calc(80 * var(--u));font-style:normal;font-size:calc(48 * var(--u));color:#fff;top:calc(100 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3091" />
</div>
    <a href="mailto:info@vivewheels.com?subject=VI-1%20Specifications" class="editorial-link wipe-control" style="position:absolute;border-width:calc(1 * var(--u));border-style:solid;border-color:#fff;align-content:stretch;display:flex;align-items:flex-start;left:calc(1668 * var(--u));padding-left:calc(24 * var(--u));padding-right:calc(24 * var(--u));padding-top:calc(10 * var(--u));padding-bottom:calc(10 * var(--u));top:calc(116 * var(--u))" data-design-node="727:3092">      <div style="align-content:stretch;display:flex;gap:calc(8 * var(--u));align-items:center;position:relative;flex-shrink:0" data-design-node="727:3093">        <p style="overflow-wrap:break-word;font-family:'Space Mono',monospace;line-height:calc(20 * var(--u));font-style:normal;position:relative;flex-shrink:0;font-size:calc(16 * var(--u));color:#fff;text-transform:uppercase;white-space:nowrap" data-design-node="727:3094"> learn more </p>
        <div style="position:relative;flex-shrink:0;width:calc(16 * var(--u));height:calc(16 * var(--u))" data-design-node="727:3095">          <ArrowIcon />
</div>
</div>
</a>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;text-transform:capitalize;font-family:'Space Mono',monospace;line-height:calc(30 * var(--u));left:calc(80 * var(--u));font-style:normal;font-size:calc(28 * var(--u));color:#fff;top:calc(270 * var(--u));white-space:nowrap" data-design-node="727:3097"> 15×7J </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;text-transform:capitalize;font-family:'Space Mono',monospace;line-height:calc(30 * var(--u));left:calc(80 * var(--u));font-style:normal;font-size:calc(28 * var(--u));color:#fff;top:calc(1776 * var(--u));white-space:nowrap" data-design-node="727:3098"> 15×7J </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;text-transform:capitalize;font-family:'Space Mono',monospace;line-height:calc(30 * var(--u));left:calc(80 * var(--u));font-style:normal;font-size:calc(28 * var(--u));color:#fff;top:calc(772 * var(--u));white-space:nowrap" data-design-node="727:3099"> 15×8J </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;text-transform:capitalize;font-family:'Space Mono',monospace;line-height:calc(30 * var(--u));left:calc(80 * var(--u));font-style:normal;font-size:calc(28 * var(--u));color:#fff;top:calc(1274 * var(--u));white-space:nowrap" data-design-node="727:3100"> 15×8J </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;text-transform:capitalize;font-family:'Space Mono',monospace;line-height:calc(30 * var(--u));left:calc(980 * var(--u));font-style:normal;font-size:calc(28 * var(--u));color:#fff;top:calc(270 * var(--u));white-space:nowrap" data-design-node="727:3101"> 15×7J </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;text-transform:capitalize;font-family:'Space Mono',monospace;line-height:calc(30 * var(--u));left:calc(980 * var(--u));font-style:normal;font-size:calc(28 * var(--u));color:#fff;top:calc(1776 * var(--u));white-space:nowrap" data-design-node="727:3102"> 15×7J </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;text-transform:capitalize;font-family:'Space Mono',monospace;line-height:calc(30 * var(--u));left:calc(980 * var(--u));font-style:normal;font-size:calc(28 * var(--u));color:#fff;top:calc(772 * var(--u));white-space:nowrap" data-design-node="727:3103"> 15×8J </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;text-transform:capitalize;font-family:'Space Mono',monospace;line-height:calc(30 * var(--u));left:calc(980 * var(--u));font-style:normal;font-size:calc(28 * var(--u));color:#fff;top:calc(1274 * var(--u));white-space:nowrap" data-design-node="727:3104"> 15×8J </p>
    <div style="position:absolute;height:0;left:calc(80 * var(--u));top:calc(324 * var(--u));width:calc(860 * var(--u))" data-design-node="727:3105">      <div style="position:absolute;inset:calc(-0.5 * var(--u)) 0">        <img :src="asset('product-details/c575f.svg')" alt="" loading="lazy" style="display:block;max-width:none;width:100%;height:100%" />
</div>
</div>
    <div style="position:absolute;height:0;left:calc(80 * var(--u));top:calc(1830 * var(--u));width:calc(860 * var(--u))" data-design-node="727:3106">      <div style="position:absolute;inset:calc(-0.5 * var(--u)) 0">        <img :src="asset('product-details/c575f.svg')" alt="" loading="lazy" style="display:block;max-width:none;width:100%;height:100%" />
</div>
</div>
    <div style="position:absolute;height:0;left:calc(80 * var(--u));top:calc(826 * var(--u));width:calc(860 * var(--u))" data-design-node="727:3107">      <div style="position:absolute;inset:calc(-0.5 * var(--u)) 0">        <img :src="asset('product-details/c575f.svg')" alt="" loading="lazy" style="display:block;max-width:none;width:100%;height:100%" />
</div>
</div>
    <div style="position:absolute;height:0;left:calc(80 * var(--u));top:calc(1328 * var(--u));width:calc(860 * var(--u))" data-design-node="727:3108">      <div style="position:absolute;inset:calc(-0.5 * var(--u)) 0">        <img :src="asset('product-details/c575f.svg')" alt="" loading="lazy" style="display:block;max-width:none;width:100%;height:100%" />
</div>
</div>
    <div style="position:absolute;height:0;left:calc(980 * var(--u));top:calc(324 * var(--u));width:calc(860 * var(--u))" data-design-node="727:3109">      <div style="position:absolute;inset:calc(-0.5 * var(--u)) 0">        <img :src="asset('product-details/c575f.svg')" alt="" loading="lazy" style="display:block;max-width:none;width:100%;height:100%" />
</div>
</div>
    <div style="position:absolute;height:0;left:calc(980 * var(--u));top:calc(1830 * var(--u));width:calc(860 * var(--u))" data-design-node="727:3110">      <div style="position:absolute;inset:calc(-0.5 * var(--u)) 0">        <img :src="asset('product-details/c575f.svg')" alt="" loading="lazy" style="display:block;max-width:none;width:100%;height:100%" />
</div>
</div>
    <div style="position:absolute;height:0;left:calc(980 * var(--u));top:calc(826 * var(--u));width:calc(860 * var(--u))" data-design-node="727:3111">      <div style="position:absolute;inset:calc(-0.5 * var(--u)) 0">        <img :src="asset('product-details/c575f.svg')" alt="" loading="lazy" style="display:block;max-width:none;width:100%;height:100%" />
</div>
</div>
    <div style="position:absolute;height:0;left:calc(980 * var(--u));top:calc(1328 * var(--u));width:calc(860 * var(--u))" data-design-node="727:3112">      <div style="position:absolute;inset:calc(-0.5 * var(--u)) 0">        <img :src="asset('product-details/c575f.svg')" alt="" loading="lazy" style="display:block;max-width:none;width:100%;height:100%" />
</div>
</div>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(348 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3113"> FACE：f1 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1854 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3114"> FACE：f1 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(850 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3115"> FACE：f3 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1352 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3116"> FACE：f3 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(348 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3117"> FACE：f2 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1854 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3118"> FACE：f2 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(850 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3119"> FACE：f3 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1352 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3120"> FACE：f3 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(428 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3121"> Hub Clearance(mm)：（43） </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1934 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3122"> Hub Clearance(mm)：（43） </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(930 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3123"> Hub Clearance(mm)：（34） </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1432 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3124"> Hub Clearance(mm)：（34） </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(428 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3125"> Hub Clearance(mm)：（43） </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1934 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3126"> Hub Clearance(mm)：（43） </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(930 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3127"> Hub Clearance(mm)：（43） </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1432 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3128"> Hub Clearance(mm)：（43） </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(508 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3129"> P.C.D.：100 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(2014 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3130"> P.C.D.：100 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1010 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3131"> P.C.D.：100 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1512 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3132"> P.C.D.：100 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(508 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3133"> P.C.D.：100 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(2014 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3134"> P.C.D.：100 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1010 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3135"> P.C.D.：100 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1512 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3136"> P.C.D.：100 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(588 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3137"> DRILL (φ)：29-13 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(2094 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3138"> DRILL (φ)：29-13 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1090 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3139"> DRILL (φ)：29-13 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1592 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3140"> DRILL (φ)：29-13 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(588 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3141"> DRILL (φ)：29-13 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(2094 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3142"> DRILL (φ)：29-13 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1090 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3143"> DRILL (φ)：29-13 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1592 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3144"> DRILL (φ)：29-13 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(388 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3145"> INSET：35 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1894 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3146"> INSET：35 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(890 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3147"> INSET：35 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1392 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3148"> INSET：35 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(388 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3149"> INSET：25 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1894 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3150"> INSET：25 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(890 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3151"> INSET：25 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1392 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3152"> INSET：25 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(468 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3153"> HOLE：4 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1974 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3154"> HOLE：4 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(970 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3155"> HOLE：4 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1472 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3156"> HOLE：4 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(468 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3157"> HOLE：4 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1974 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3158"> HOLE：4 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(970 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3159"> HOLE：4 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1472 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3160"> HOLE：4 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(548 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3161"> HUB BORE (φ)：65 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(2054 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3162"> HUB BORE (φ)：65 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1050 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3163"> HUB BORE (φ)：65 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1552 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3164"> HUB BORE (φ)：65 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(548 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3165"> HUB BORE (φ)：65 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(2054 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3166"> HUB BORE (φ)：65 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1050 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3167"> HUB BORE (φ)：65 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1552 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap;font-variation-settings:&quot;CTGR&quot; 0, &quot;wdth&quot; 100" data-design-node="727:3168"> HUB BORE (φ)：65 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(628 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3169"> COLOR：bl </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(2134 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3170"> COLOR：bl </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1130 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3171"> COLOR：bl </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1632 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3172"> COLOR：bl </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(628 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3173"> COLOR：bl </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(2134 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3174"> COLOR：bl </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1130 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3175"> COLOR：bl </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1632 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3176"> COLOR：bl </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(668 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3177"> PRICE：¥74,000 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(2174 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3178"> PRICE：¥74,000 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1170 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3179"> PRICE：¥77,000 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(80 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1672 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3180"> PRICE：¥77,000 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(668 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3181"> PRICE：¥74,000 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(2174 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3182"> PRICE：¥74,000 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1170 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3183"> PRICE：¥77,000 </p>
    <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;font-weight:400;line-height:calc(24 * var(--u));left:calc(980 * var(--u));overflow:hidden;font-size:calc(20 * var(--u));color:#fff;top:calc(1672 * var(--u));letter-spacing:calc(0.8 * var(--u));text-transform:uppercase;white-space:nowrap" data-design-node="727:3184"> PRICE：¥77,000 </p>
</section>
  <PerformanceStory />
  <section class="detail-editorial-section" style="position:relative;background:#0e0f0f;height:calc(370 * var(--u));left:auto;overflow:clip;top:auto;width:calc(1920 * var(--u));translate:none" data-design-node="727:2878">    <div style="position:absolute;display:contents;left:calc(80 * var(--u));top:calc(100 * var(--u))" data-design-node="727:2879">      <div style="position:absolute;left:calc(300 * var(--u));overflow:clip;width:calc(60 * var(--u));height:calc(60 * var(--u));top:calc(100 * var(--u))" data-design-node="727:2880">        <div style="position:absolute;inset:8.33%" data-design-node="727:2881">          <div style="position:absolute;inset:-2%">            <img :src="asset('product-details/5ff31.svg')" alt="" loading="lazy" style="display:block;max-width:none;width:100%;height:100%" />
</div>
</div>
</div>
      <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;text-transform:capitalize;font-family:'Space Mono',monospace;line-height:calc(30 * var(--u));left:calc(330 * var(--u));font-style:normal;font-size:calc(28 * var(--u));text-align:center;color:#fff;top:calc(184 * var(--u));white-space:nowrap;translate:-50% 0" data-design-node="727:2888"> Fitment Is A System </p>
      <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;line-height:calc(24 * var(--u));left:calc(330 * var(--u));font-style:normal;font-size:calc(16 * var(--u));color:rgba(255,255,255,0.8);text-align:center;top:calc(222 * var(--u));width:calc(500 * var(--u));translate:-50% 0" data-design-node="727:2889"> Fitment goes beyond whether a wheel can be installed. </p>
</div>
    <div style="position:absolute;display:contents;left:50%;top:calc(100 * var(--u));translate:-50% 0" data-design-node="727:2890">      <div style="position:absolute;left:50%;width:calc(60 * var(--u));height:calc(60 * var(--u));top:calc(100 * var(--u));translate:-50% 0" data-design-node="727:2891">        <img :src="asset('product-details/c651e.svg')" alt="" loading="lazy" style="position:absolute;display:block;inset:0;max-width:none;width:100%;height:100%" />
</div>
      <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;text-transform:capitalize;font-family:'Space Mono',monospace;line-height:calc(30 * var(--u));left:50%;font-style:normal;font-size:calc(28 * var(--u));text-align:center;color:#fff;top:calc(184 * var(--u));white-space:nowrap;translate:-50% 0" data-design-node="727:2899"> Engineering Validation </p>
      <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;line-height:calc(24 * var(--u));left:50%;font-style:normal;font-size:calc(16 * var(--u));color:rgba(255,255,255,0.8);text-align:center;top:calc(222 * var(--u));width:calc(500 * var(--u));translate:-50% 0" data-design-node="727:2900"> continuously refining the product toward its defined engineering targets. </p>
</div>
    <div style="position:absolute;display:contents;left:calc(50% + calc(630 * var(--u)));top:calc(100 * var(--u));translate:-50% 0" data-design-node="727:2901">      <div style="position:absolute;left:calc(50% + calc(630 * var(--u)));width:calc(60 * var(--u));height:calc(60 * var(--u));top:calc(100 * var(--u));translate:-50% 0" data-design-node="727:2902">        <img :src="asset('product-details/d1ec7.svg')" alt="" loading="lazy" style="position:absolute;display:block;inset:0;max-width:none;width:100%;height:100%" />
</div>
      <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;text-transform:capitalize;font-family:'Space Mono',monospace;line-height:calc(30 * var(--u));left:calc(50% + calc(630 * var(--u)));font-style:normal;font-size:calc(28 * var(--u));text-align:center;color:#fff;top:calc(184 * var(--u));white-space:nowrap;translate:-50% 0" data-design-node="727:2912"> The Same Standard </p>
      <p data-reveal="fade" style="overflow-wrap:break-word;position:absolute;font-family:'Space Mono',monospace;line-height:calc(24 * var(--u));left:calc(50% + calc(630 * var(--u)));font-style:normal;font-size:calc(16 * var(--u));color:rgba(255,255,255,0.8);text-align:center;top:calc(222 * var(--u));width:calc(500 * var(--u));translate:-50% 0" data-design-node="727:2913"> VIVE Street does not follow a single visual formula. </p>
</div>
</section>
  <DetailCraft />
  <ProductGallery />
</template>
<style>
.detail-editorial-section { isolation:isolate; }
.editorial-link{color:white}.editorial-link p{color:inherit!important}
.editorial-link .vive-arrow{display:block}
</style>
